apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  name: developer
  namespace: blue
rules:
- apiGroups:
  - apps
  resourceNames:
  - blue-app
  - dark-blue-app
  resources:
  - pods
  verbs:
  - get
  - watch
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create